name: Release to Maven Central

on:
  push:
    branches:
      - main  # Deployment nur bei Merge in main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Setup JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}

      # 3️⃣ Import GPG key
      - name: Import GPG key
        run: |
          echo "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | base64 --decode | gpg --batch --import
          gpg --list-secret-keys

      # 4️⃣ Build and deploy to Maven Central
      - name: Build and Deploy
        run: mvn clean deploy -B -U \
              -Dgpg.passphrase="${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}" \
              -DskipTests=false
